CREATE PROCEDURE [dbo].[p_GetAD_Definations]
/***********************************************************
* Code generated by SoftTree SQL Assistant © v7.5.502
*
* Procedure description: This procedure is used for 
*                        retrieving records from table 
*                        AD_Definations
* Date:   12/29/2016 
* Author: muhammad.muzzammil
*
* Changes
* Date        Modified By            Comments
************************************************************
* 12/29/2016  muhammad.muzzammil     Initial version
************************************************************/
(
    @DefinationId numeric(18,0)
)
AS
BEGIN
    SET NOCOUNT ON
    DECLARE @rowcount INT, @error INT

    -- search and return records
    SELECT DefinationId,
           DefinationName,
           PDefinationId,
           DefinationTypeId,
           KeyCode,
           DisplayType,
           ColorCode,
           InputType,
           MaxLength,
           SortOrder,
           IsActive 
    FROM [dbo].[AD_Definations]
    WHERE  DefinationId = @DefinationId

     -- capture operation completion code and number of records affected
	SELECT @rowcount = @@ROWCOUNT, 
           @error = @@ERROR

	IF @error != 0
    BEGIN
		-- report error and exit with non-zero exit code
        RAISERROR('Unable to retrieve records. See previous message for details.', 16, 1) 
		RETURN @error
    END
    IF @rowcount = 0
    BEGIN
		-- report error and exit with non-zero exit code
        RAISERROR('Critical error. No records found for the specified criteria.', 16, 1) 
		RETURN 1
    END 
    IF @rowcount > 1 
    BEGIN
		-- report error and exit with non-zero exit code
        RAISERROR('Warning. More than 1 record found for the specified criteria, while just 1 is expected.', 10, 1) 
		RETURN 1
    END 

    -- commit changes and return 0 code indicating successful completion
	RETURN 0
END