CREATE PROCEDURE [dbo].[p_SaveAD_Definations]
/***********************************************************
* Code generated by SoftTree SQL Assistant © v7.5.502
*
* Procedure description: This procedure is used for adding 
*                        and updating records in table 
*                        AD_Definations
* Date:   12/29/2016 
* Author: muhammad.muzzammil
*
* Changes
* Date        Modified By            Comments
************************************************************
* 12/29/2016  muhammad.muzzammil     Initial version
************************************************************/
(
    @DefinationId numeric(18,0) = NULL,
    @DefinationName varchar(100) = NULL,
    @PDefinationId numeric(18,0) = NULL,
    @DefinationTypeId numeric(18,0) = NULL,
    @KeyCode nvarchar(50) = NULL,
    @DisplayType nvarchar(50) = NULL,
    @ColorCode nvarchar(50) = NULL,
    @InputType nvarchar(50) = NULL,
    @MaxLength int = NULL,
    @SortOrder int = NULL,
    @IsActive bit = NULL
)
AS
BEGIN
    SET NOCOUNT ON
    DECLARE @rowcount INT, @error INT, @id INT

    -- start transaction
	BEGIN TRANSACTION

    -- check if the specified record already exists, if yes, update it, if no, create it
    IF NOT EXISTS 
    (    
         SELECT * 
         FROM [dbo].[AD_Definations]
         WHERE  DefinationId = @DefinationId
    )
    BEGIN 
         -- insert new record
         INSERT INTO [dbo].[AD_Definations]
         (
             DefinationName,
             PDefinationId,
             DefinationTypeId,
             KeyCode,
             DisplayType,
             ColorCode,
             InputType,
             MaxLength,
             SortOrder,
             IsActive
         )
         VALUES 
         (
             @DefinationName,
             @PDefinationId,
             @DefinationTypeId,
             @KeyCode,
             @DisplayType,
             @ColorCode,
             @InputType,
             @MaxLength,
             @SortOrder,
             @IsActive
         )
    END 
    ELSE
    BEGIN
         -- update existing record
         UPDATE [dbo].[AD_Definations]
         SET DefinationName = @DefinationName,
             PDefinationId = @PDefinationId,
             DefinationTypeId = @DefinationTypeId,
             KeyCode = @KeyCode,
             DisplayType = @DisplayType,
             ColorCode = @ColorCode,
             InputType = @InputType,
             MaxLength = @MaxLength,
             SortOrder = @SortOrder,
             IsActive = @IsActive
         WHERE  DefinationId = @DefinationId
    END

    -- capture operation completion code and number of records affected
	SELECT @rowcount = @@ROWCOUNT, 
           @error = @@ERROR,
           @id = SCOPE_IDENTITY()

	IF @error != 0
    BEGIN
        -- cancel transaction, undo changes
        ROLLBACK TRANSACTION

		-- report error and exit with non-zero exit code
        RAISERROR('Unable to update or insert new record. See previous message for details.', 16, 1) 
		RETURN @error
    END
    IF @rowcount != 1 
    BEGIN
        -- cancel transaction, undo changes
        ROLLBACK TRANSACTION

		-- report error and exit with non-zero exit code
        RAISERROR('Critical error. More than 1 record found for the specified criteria, just 1 is expected.', 16, 1) 
		RETURN 1
    END 

    -- commit changes and return 0 code indicating successful completion
    COMMIT TRANSACTION

	-- if operation type 'Add record', return result set with the last inserted column value 
    IF @id IS NOT NULL
        SELECT @id AS NewRecordID
    RETURN 0
END