CREATE TABLE [dbo].[AAPLAN] (
    [FA_Code]                                   NVARCHAR (MAX) NULL,
    [USID]                                      NVARCHAR (MAX) NULL,
    [Common ID]                                 NVARCHAR (255) NULL,
    [REGION]                                    NVARCHAR (255) NULL,
    [MARKET]                                    NVARCHAR (255) NULL,
    [SUB Market]                                NVARCHAR (255) NULL,
    [Site Name]                                 NVARCHAR (255) NULL,
    [Street_Address]                            NVARCHAR (255) NULL,
    [CITY]                                      NVARCHAR (255) NULL,
    [State]                                     NVARCHAR (255) NULL,
    [ZIP]                                       NVARCHAR (MAX) NULL,
    [COUNTY]                                    NVARCHAR (255) NULL,
    [Latitude]                                  NVARCHAR (MAX) NULL,
    [Longitude]                                 NVARCHAR (MAX) NULL,
    [vMME]                                      NVARCHAR (MAX) NULL,
    [Controlled Introduction]                   NVARCHAR (MAX) NULL,
    [Super Bowl]                                NVARCHAR (MAX) NULL,
    [Site_Type]                                 NVARCHAR (255) NULL,
    [DAS_or_Inbuilding]                         NVARCHAR (255) NULL,
    [FirstNet RAN]                              NVARCHAR (255) NULL,
    [iPlan Job]                                 NVARCHAR (255) NULL,
    [iPlan Status]                              NVARCHAR (255) NULL,
    [iPlan Issue Date]                          NVARCHAR (MAX) NULL,
    [PACE Number]                               NVARCHAR (255) NULL,
    [TSS_Plan]                                  NVARCHAR (255) NULL,
    [TSS_Forecast]                              NVARCHAR (255) NULL,
    [TSS_Submitted]                             NVARCHAR (255) NULL,
    [Site_Specific_Material_Available_Forecast] NVARCHAR (255) NULL,
    [Site_Specific_Material_Available_Actual]   NVARCHAR (255) NULL,
    [Pre_Install_Planned]                       NVARCHAR (255) NULL,
    [Pre_Install_Fcst]                          NVARCHAR (MAX) NULL,
    [Pre_Install_Actual]                        NVARCHAR (255) NULL,
    [Mig_Date_Planned]                          NVARCHAR (255) NULL,
    [Mig_Date_Forecast]                         NVARCHAR (255) NULL,
    [Migration Date]                            NVARCHAR (MAX) NULL,
    [EPL Ordered]                               NVARCHAR (MAX) NULL,
    [EPL Called Out]                            NVARCHAR (MAX) NULL,
    [EPL Delivered]                             NVARCHAR (MAX) NULL,
    [EPL Status]                                NVARCHAR (255) NULL
);

