CREATE TABLE [dbo].[ATT_Sites] (
    [Id]                                        NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [FA_Code]                                   NVARCHAR (255) NULL,
    [USID]                                      NVARCHAR (255) NULL,
    [Common ID]                                 NVARCHAR (255) NULL,
    [REGION]                                    NVARCHAR (255) NULL,
    [MARKET]                                    NVARCHAR (255) NULL,
    [SUB Market]                                NVARCHAR (255) NULL,
    [Site Name]                                 NVARCHAR (255) NULL,
    [Street_Address]                            NVARCHAR (255) NULL,
    [CITY]                                      NVARCHAR (255) NULL,
    [State]                                     NVARCHAR (255) NULL,
    [ZIP]                                       NVARCHAR (255) NULL,
    [COUNTY]                                    NVARCHAR (255) NULL,
    [Latitude]                                  FLOAT (53)     NULL,
    [Longitude]                                 FLOAT (53)     NULL,
    [vMME]                                      BIT            NOT NULL,
    [Controlled Introduction]                   BIT            NOT NULL,
    [Super Bowl]                                BIT            NOT NULL,
    [Site_Type]                                 NVARCHAR (255) NULL,
    [DAS_or_Inbuilding]                         NVARCHAR (255) NULL,
    [FirstNet RAN]                              NVARCHAR (255) NULL,
    [iPlan Job]                                 NVARCHAR (255) NULL,
    [iPlan Status]                              NVARCHAR (255) NULL,
    [PACE Number]                               NVARCHAR (255) NULL,
    [iPlan Issue Date]                          DATETIME       NULL,
    [TSS_Plan]                                  DATETIME       NULL,
    [TSS_Forecast]                              DATETIME       NULL,
    [TSS_Submitted]                             DATETIME       NULL,
    [Site_Specific_Material_Available_Forecast] DATETIME       NULL,
    [Site_Specific_Material_Available_Actual]   DATETIME       NULL,
    [Pre_Install_Planned]                       DATETIME       NULL,
    [Pre_Install_Fcst]                          DATETIME       NULL,
    [Pre_Install_Actual]                        DATETIME       NULL,
    [Mig_Date_Planned]                          DATETIME       NULL,
    [Mig_Date_Forecast]                         DATETIME       NULL,
    [Migration Date]                            DATETIME       NULL,
    CONSTRAINT [PK_ATT_Sites] PRIMARY KEY CLUSTERED ([Id] ASC)
);

