CREATE TABLE [dbo].[AV_BeamTestLog] (
    [BTLogId]       INT           IDENTITY (1, 1) NOT NULL,
    [TimeStamp]     DATETIME      NOT NULL,
    [SiteId]        NUMERIC (18)  NOT NULL,
    [NetworkModeId] NUMERIC (18)  NOT NULL,
    [ScopeId]       NUMERIC (18)  NULL,
    [BandId]        NUMERIC (18)  NOT NULL,
    [CarrierId]     NUMERIC (18)  NOT NULL,
    [LayerStatusId] NUMERIC (18)  NULL,
    [BeamGroupId]   INT           NOT NULL,
    [BeamId]        INT           NOT NULL,
    [BMGColor]      NVARCHAR (10) NULL,
    [BMColor]       NVARCHAR (10) NULL,
    [Latitude]      FLOAT (53)    NOT NULL,
    [Longitude]     FLOAT (53)    NOT NULL,
    [PCIId]         INT           NOT NULL,
    [SSBIndex]      INT           NOT NULL,
    [NRRSRP0]       FLOAT (53)    NOT NULL,
    [NRRSRP1]       FLOAT (53)    NOT NULL,
    [NRRSRP2]       FLOAT (53)    NOT NULL,
    [NRRSRP3]       FLOAT (53)    NOT NULL,
    [NRRSRQ0]       FLOAT (53)    NOT NULL,
    [NRRSRQ1]       FLOAT (53)    NOT NULL,
    [NRRSRQ2]       FLOAT (53)    NOT NULL,
    [NRRSRQ3]       FLOAT (53)    NOT NULL,
    [NRRSNR0]       FLOAT (53)    NOT NULL,
    [NRRSNR1]       FLOAT (53)    NOT NULL,
    [NRRSNR2]       FLOAT (53)    NOT NULL,
    [NRRSNR3]       FLOAT (53)    NOT NULL,
    [SectorId]      NUMERIC (18)  NULL
);

