CREATE TABLE [dbo].[AV_ClusterSchedule] (
    [DeviceScheduleId]     NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SiteClusterId]        NUMERIC (18)   NULL,
    [LayerStatusId]        NUMERIC (18)   NULL,
    [SiteId]               NUMERIC (18)   NULL,
    [ScopeId]              NUMERIC (18)   NULL,
    [WoRefId]              NVARCHAR (50)  NULL,
    [DownloadDate]         DATETIME       NULL,
    [IsDownloaded]         BIT            CONSTRAINT [DF_AV_ClusterSchedule_IsDownlaoded] DEFAULT ((0)) NULL,
    [UserId]               NUMERIC (18)   NULL,
    [UserDeviceId]         NUMERIC (18)   NULL,
    [SiteScriptId]         NUMERIC (18)   NULL,
    [SequenceId]           INT            NULL,
    [TestTypes]            NVARCHAR (100) NULL,
    [TesterId]             NUMERIC (18)   NULL,
    [ReceivedOn]           DATETIME       CONSTRAINT [DF_AV_ClusterSchedule_ReceivedOn] DEFAULT (getdate()) NULL,
    [UploadedOn]           DATETIME       CONSTRAINT [DF_AV_ClusterSchedule_SubmittedOn] DEFAULT (getdate()) NULL,
    [AssignedOn]           DATETIME       NULL,
    [CompletedOn]          DATETIME       NULL,
    [ScheduledOn]          DATETIME       NULL,
    [DriveCompletedOn]     DATETIME       NULL,
    [DownloadedOn]         DATETIME       NULL,
    [SubmittedOn]          DATETIME       NULL,
    [AcceptedOn]           DATETIME       NULL,
    [UploadedById]         NUMERIC (18)   NULL,
    [ScheduledById]        NUMERIC (18)   CONSTRAINT [DF_AV_ClusterSchedule_TesterAssignedById] DEFAULT ((0)) NULL,
    [SubmittedById]        NUMERIC (18)   NULL,
    [AcceptedById]         NUMERIC (18)   NULL,
    [Status]               NUMERIC (18)   NULL,
    [StatusReason]         NUMERIC (18)   NULL,
    [PendingIssueDesc]     NVARCHAR (500) NULL,
    [IsActive]             BIT            CONSTRAINT [DF_AV_ClusterSchedule_IsActive] DEFAULT ((1)) NOT NULL,
    [IsPublished]          BIT            CONSTRAINT [DF_AV_ClusterSchedule_IsPublished] DEFAULT ((0)) NULL,
    [PublishedOn]          DATETIME       NULL,
    [isRedrive]            BIT            CONSTRAINT [DF_AV_ClusterSchedule_isRedrive] DEFAULT ((0)) NULL,
    [redriveTypeId]        INT            NULL,
    [redriveReasonId]      INT            NULL,
    [PWoRefID]             NVARCHAR (50)  NULL,
    [redriveComments]      NVARCHAR (500) NULL,
    [netLayerObservations] NVARCHAR (500) NULL,
    [pendingWithIssueOn]   DATETIME       NULL,
    [pendingWithIssueById] NUMERIC (18)   NULL,
    [IsMaster]             BIT            NULL,
    CONSTRAINT [PK_AV_ClusterSchedule] PRIMARY KEY CLUSTERED ([DeviceScheduleId] ASC)
);

