CREATE TABLE [dbo].[AV_NeighbourLogs] (
    [NLogId]        NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [SiteId]        NUMERIC (18)  NULL,
    [NetworkModeId] NUMERIC (18)  NULL,
    [BandId]        NUMERIC (18)  NULL,
    [CarrierId]     NUMERIC (18)  NULL,
    [SectorId]      NUMERIC (18)  NULL,
    [TimeStamp]     DATETIME      NULL,
    [NetMode1]      NVARCHAR (15) NULL,
    [Band1]         NVARCHAR (15) NULL,
    [CH1]           NVARCHAR (15) NULL,
    [PCI1]          INT           NULL,
    [CI1]           FLOAT (53)    NULL,
    [SS1]           FLOAT (53)    NULL,
    [SP1]           FLOAT (53)    NULL,
    [SQ1]           FLOAT (53)    NULL,
    [SNR1]          FLOAT (53)    NULL,
    [NetMode2]      NVARCHAR (15) NULL,
    [Band2]         NVARCHAR (15) NULL,
    [CH2]           NVARCHAR (15) NULL,
    [PCI2]          INT           NULL,
    [CI2]           FLOAT (53)    NULL,
    [SS2]           FLOAT (53)    NULL,
    [SP2]           FLOAT (53)    NULL,
    [SQ2]           FLOAT (53)    NULL,
    [SNR2]          FLOAT (53)    NULL,
    [NetMode3]      NVARCHAR (15) NULL,
    [Band3]         NVARCHAR (15) NULL,
    [CH3]           NVARCHAR (15) NULL,
    [PCI3]          INT           NULL,
    [CI3]           FLOAT (53)    NULL,
    [SS3]           FLOAT (53)    NULL,
    [SP3]           FLOAT (53)    NULL,
    [SQ3]           FLOAT (53)    NULL,
    [SNR3]          FLOAT (53)    NULL,
    [NetMode4]      NVARCHAR (15) NULL,
    [Band4]         NVARCHAR (15) NULL,
    [CH4]           NVARCHAR (15) NULL,
    [PCI4]          INT           NULL,
    [CI4]           FLOAT (53)    NULL,
    [SS4]           FLOAT (53)    NULL,
    [SP4]           FLOAT (53)    NULL,
    [SQ4]           FLOAT (53)    NULL,
    [SNR4]          FLOAT (53)    NULL,
    [NetMode5]      NVARCHAR (15) NULL,
    [Band5]         NVARCHAR (15) NULL,
    [CH5]           NVARCHAR (15) NULL,
    [PCI5]          INT           NULL,
    [CI5]           FLOAT (53)    NULL,
    [SS5]           FLOAT (53)    NULL,
    [SP5]           FLOAT (53)    NULL,
    [SQ5]           FLOAT (53)    NULL,
    [SNR5]          FLOAT (53)    NULL,
    [NetMode6]      NVARCHAR (15) NULL,
    [Band6]         NVARCHAR (15) NULL,
    [CH6]           NVARCHAR (15) NULL,
    [PCI6]          INT           NULL,
    [CI6]           FLOAT (53)    NULL,
    [SS6]           FLOAT (53)    NULL,
    [SP6]           FLOAT (53)    NULL,
    [SQ6]           FLOAT (53)    NULL,
    [SNR6]          FLOAT (53)    NULL,
    [NetMode7]      NVARCHAR (15) NULL,
    [Band7]         NVARCHAR (15) NULL,
    [CH7]           NVARCHAR (15) NULL,
    [PCI7]          INT           NULL,
    [CI7]           FLOAT (53)    NULL,
    [SS7]           FLOAT (53)    NULL,
    [SP7]           FLOAT (53)    NULL,
    [SQ7]           FLOAT (53)    NULL,
    [SNR7]          FLOAT (53)    NULL,
    [NetMode8]      NVARCHAR (15) NULL,
    [Band8]         NVARCHAR (15) NULL,
    [CH8]           NVARCHAR (15) NULL,
    [PCI8]          INT           NULL,
    [CI8]           FLOAT (53)    NULL,
    [SS8]           FLOAT (53)    NULL,
    [SP8]           FLOAT (53)    NULL,
    [SQ8]           FLOAT (53)    NULL,
    [SNR8]          FLOAT (53)    NULL,
    CONSTRAINT [PK_AV_NeighbourLogs] PRIMARY KEY CLUSTERED ([NLogId] ASC)
);

