CREATE TABLE [dbo].[AV_TestLocation] (
    [TestLocationId]   NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [SiteId]           NUMERIC (18)   NULL,
    [NetworkModeId]    NUMERIC (18)   NULL,
    [BandId]           NUMERIC (18)   NULL,
    [CarrierId]        NUMERIC (18)   NULL,
    [ScopeId]          NUMERIC (18)   NULL,
    [TestCategory]     VARCHAR (50)   NULL,
    [TestType]         VARCHAR (50)   NULL,
    [TestResult]       FLOAT (53)     NULL,
    [Latitude]         FLOAT (53)     NULL,
    [Longitude]        FLOAT (53)     NULL,
    [SignalStrength]   FLOAT (53)     NULL,
    [SignalQuality]    FLOAT (53)     NULL,
    [SignalNoiseRatio] FLOAT (53)     NOT NULL,
    [TestComments]     NVARCHAR (50)  NULL,
    [TestDate]         DATETIME       NULL,
    [TestStatus]       BIT            NULL,
    [TestKPI]          FLOAT (53)     NULL,
    [SectorId]         NUMERIC (18)   NULL,
    [SourceCell]       NVARCHAR (5)   NULL,
    [TargetCell]       NVARCHAR (5)   NULL,
    [PRBPercent]       FLOAT (53)     NULL,
    [MCS]              NVARCHAR (100) NULL,
    [RB]               INT            NULL,
    [Modulation]       NVARCHAR (50)  NULL,
    [ModPercent]       NVARCHAR (100) NULL,
    [TM]               NVARCHAR (50)  NULL,
    [RI]               INT            NULL,
    [PDSCH]            FLOAT (53)     NULL,
    [CAPDSCH]          FLOAT (53)     NULL,
    [PUSCH]            FLOAT (53)     NULL,
    [CAPU]             FLOAT (53)     NULL,
    CONSTRAINT [PK_AV_TestLocation] PRIMARY KEY CLUSTERED ([TestLocationId] ASC)
);

