CREATE TABLE [dbo].[FM_VehicleTrackingLog] (
    [TrackingId]         INT             IDENTITY (1, 1) NOT NULL,
    [VehicleId]          INT             NULL,
    [Input]              TEXT            NULL,
    [CreatedOn]          ROWVERSION      NOT NULL,
    [Latitude]           DECIMAL (12, 9) NULL,
    [Longitude]          DECIMAL (12, 9) NULL,
    [Speed]              DECIMAL (18)    NULL,
    [Odometer]           DECIMAL (18)    NULL,
    [Direction]          DECIMAL (18)    NULL,
    [Rotation]           VARCHAR (20)    NULL,
    [Altitude]           DECIMAL (18)    NULL,
    [TrackerStream]      TEXT            NULL,
    [GPSSignalStatus]    VARCHAR (10)    NULL,
    [UTCTimeAndDate]     DATETIME        NULL,
    [IMEI]               VARCHAR (50)    NULL,
    [trackTimeStamp]     DATETIME        NULL,
    [OutLockthedoor]     BIT             NULL,
    [OutSirenSound]      BIT             NULL,
    [OutUnlockthedoor]   BIT             NULL,
    [OutRelyToStopCar]   BIT             NULL,
    [InSOS]              BIT             NULL,
    [InAntiTemper]       BIT             NULL,
    [InDoorOpenClose]    BIT             NULL,
    [InUnlockDoor]       BIT             NULL,
    [InEngineOnOff]      BIT             NULL,
    [IsOfflineData]      BIT             NULL,
    [FuelPercent]        INT             NULL,
    [FuelLiter]          FLOAT (53)      NULL,
    [CurrentTripMileage] FLOAT (53)      NULL,
    [Temperature]        FLOAT (53)      NULL,
    [DeviceState]        NVARCHAR (50)   NULL,
    [AssetStatus]        NVARCHAR (50)   NULL,
    [ExtendState]        NVARCHAR (50)   NULL,
    [Address]            NVARCHAR (50)   NULL,
    [GSMSignal]          NVARCHAR (50)   NULL,
    [TotalFuelConsumed]  FLOAT (53)      NULL
);

