CREATE TABLE [dbo].[FSM4_EPL] (
    [FA_Code]               FLOAT (53)     NULL,
    [Site Name]             NVARCHAR (255) NULL,
    [Region]                NVARCHAR (255) NULL,
    [Customer]              NVARCHAR (255) NULL,
    [Order Number]          FLOAT (53)     NULL,
    [Project ID]            NVARCHAR (255) NULL,
    [Order Status]          NVARCHAR (255) NULL,
    [Approval Date]         DATETIME       NULL,
    [Oracle Project Number] NVARCHAR (255) NULL,
    [Created By]            NVARCHAR (255) NULL,
    [Site Required Date]    NVARCHAR (255) NULL,
    [Item Number]           NVARCHAR (255) NULL,
    [Item Description]      NVARCHAR (255) NULL,
    [Address Ship]          NVARCHAR (255) NULL,
    [City Ship]             NVARCHAR (255) NULL,
    [State]                 NVARCHAR (255) NULL,
    [Zip Ship]              NVARCHAR (255) NULL,
    [Country Ship]          NVARCHAR (255) NULL,
    [Qty]                   FLOAT (53)     NULL,
    [Callout Date]          DATETIME       NULL,
    [Shipment Date]         DATETIME       NULL,
    [Carrier]               NVARCHAR (255) NULL,
    [Carrier Tracking]      NVARCHAR (255) NULL,
    [CED]                   DATETIME       NULL,
    [Line Status]           NVARCHAR (255) NULL,
    [Line Number]           FLOAT (53)     NULL,
    [Callout Number]        NVARCHAR (255) NULL,
    [Line ID]               NVARCHAR (255) NULL,
    [Header ID]             NVARCHAR (255) NULL,
    [Delivery Date]         DATETIME       NULL,
    [CEEOT order Number]    NVARCHAR (255) NULL,
    [PACE ID]               NVARCHAR (255) NULL
);

