CREATE TABLE [dbo].[PM_Issues] (
    [IssueId]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ProjectId]       NUMERIC (18)   NULL,
    [ProjectSiteId]   NUMERIC (18)   NULL,
    [TaskTypeId]      NUMERIC (18)   NULL,
    [TaskId]          NUMERIC (18)   NULL,
    [ReasonId]        NUMERIC (18)   NULL,
    [IssueById]       NUMERIC (18)   NULL,
    [IssuePriorityId] NUMERIC (18)   NULL,
    [IssueStatusId]   NUMERIC (18)   NULL,
    [Description]     NVARCHAR (MAX) NULL,
    [RequestedById]   NUMERIC (18)   NULL,
    [RequestedBy]     NVARCHAR (50)  NULL,
    [RequestDate]     DATETIME       NULL,
    [AssignedToId]    NVARCHAR (50)  NULL,
    [ForecastDate]    DATETIME       NULL,
    [TargetDate]      DATETIME       NULL,
    [ActualStartDate] DATETIME       NULL,
    [ActualEndDate]   DATETIME       NULL,
    [Tags]            NVARCHAR (250) NULL,
    [IsUnavoidable]   BIT            NULL,
    [IssueCategoryId] NUMERIC (18)   NULL,
    [SeverityId]      NUMERIC (18)   NULL,
    [eNB]             NVARCHAR (50)  NULL,
    [ExtendedeNB]     NVARCHAR (50)  NULL,
    [EquipmentId]     NVARCHAR (50)  NULL,
    [AOTSCR]          NVARCHAR (50)  NULL,
    [ActivityTypeId]  NUMERIC (18)   NULL,
    [ItemTypeId]      NUMERIC (18)   NULL,
    [ItemFilePath]    NVARCHAR (250) NULL,
    [AlarmId]         NUMERIC (18)   NULL,
    [MSWindowId]      NUMERIC (18)   NULL,
    [StatusId]        NUMERIC (18)   NULL,
    [Created]         DATETIME       NULL,
    [CreatedBy]       NVARCHAR (50)  NULL,
    [TicketTypeId]    NUMERIC (18)   NULL,
    CONSTRAINT [PK_PM_Issues] PRIMARY KEY CLUSTERED ([IssueId] ASC)
);

