CREATE TABLE [dbo].[PM_ProjectSites] (
    [ProjectSiteId]      NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [WoRefId]            NVARCHAR (50)  NULL,
    [ProjectId]          NUMERIC (18)   NOT NULL,
    [SiteCode]           NVARCHAR (50)  NULL,
    [SiteName]           NVARCHAR (500) NULL,
    [SiteDate]           DATETIME       NULL,
    [SiteTypeId]         NUMERIC (18)   NULL,
    [SiteClassId]        NUMERIC (18)   NULL,
    [Latitude]           FLOAT (53)     NULL,
    [Longitude]          FLOAT (53)     NULL,
    [RevisionId]         INT            NULL,
    [PMCode]             INT            NULL,
    [PMRefId]            NVARCHAR (50)  NULL,
    [ClusterId]          NUMERIC (18)   NULL,
    [ClusterCode]        NVARCHAR (50)  NULL,
    [CityId]             NUMERIC (18)   NULL,
    [StatusId]           NUMERIC (18)   NULL,
    [MSWindowId]         NUMERIC (18)   NULL,
    [PriorityId]         NUMERIC (18)   NULL,
    [ColorId]            NVARCHAR (70)  NULL,
    [CreatedOn]          DATETIME       NULL,
    [CreatedBy]          NUMERIC (18)   NULL,
    [IsActive]           BIT            CONSTRAINT [DF_PM_ProjectSites_IsActive] DEFAULT ((1)) NULL,
    [BudgetCost]         FLOAT (53)     NULL,
    [ActualCost]         FLOAT (53)     NULL,
    [Description]        NVARCHAR (500) NULL,
    [ClientId]           NUMERIC (18)   NULL,
    [ScopeId]            NUMERIC (18)   NULL,
    [ReceivedOn]         DATETIME       NULL,
    [Address]            NVARCHAR (250) NULL,
    [PlannedDate]        DATETIME       NULL,
    [TargetDate]         DATETIME       NULL,
    [ActualStartDate]    DATETIME       NULL,
    [ActualEndDate]      DATETIME       NULL,
    [EstimatedStartDate] DATETIME       NULL,
    [EstimatedEndDate]   DATETIME       NULL,
    [MilestoneId]        NUMERIC (18)   NULL,
    [StageId]            NUMERIC (18)   NULL,
    [FACode]             NVARCHAR (25)  NULL,
    [USID]               NVARCHAR (25)  NULL,
    [CommonId]           NVARCHAR (25)  NULL,
    [MarketId]           NUMERIC (18)   NULL,
    [SubMarketId]        NUMERIC (18)   NULL,
    [CountyId]           NUMERIC (18)   NULL,
    [vMME]               BIT            NULL,
    [ControlledIntro]    BIT            NULL,
    [SuperBowl]          BIT            NULL,
    [isDASInBuild]       NVARCHAR (50)  NULL,
    [FirstNetRAN]        NVARCHAR (50)  NULL,
    [IPlanJob]           NVARCHAR (50)  NULL,
    [PaceNo]             NVARCHAR (50)  NULL,
    [IPlanIssueDate]     DATETIME       NULL,
    [SubMarket]          NVARCHAR (150) NULL,
    [County]             NVARCHAR (150) NULL,
    [AlarmId]            NUMERIC (18)   NULL,
    [ModifyBy]           NUMERIC (18)   NULL,
    [ModifyOn]           DATETIME       NULL,
    CONSTRAINT [PK_PM_ProjectSites_1] PRIMARY KEY CLUSTERED ([ProjectSiteId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_PM_ProjectSites]
    ON [dbo].[PM_ProjectSites]([ProjectId] ASC);

