CREATE TABLE [dbo].[PM_Projects] (
    [ProjectId]         NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [ProjectName]       NVARCHAR (150) NOT NULL,
    [ScopeId]           NVARCHAR (50)  NULL,
    [ClientId]          NUMERIC (18)   NULL,
    [EndClientId]       NUMERIC (18)   NULL,
    [PriorityId]        NUMERIC (18)   NULL,
    [StatusId]          NUMERIC (18)   NULL,
    [EstimateStartDate] DATETIME       NULL,
    [EstimateEndDate]   DATETIME       NULL,
    [ActualStartDate]   DATETIME       NULL,
    [ActualEndDate]     DATETIME       NULL,
    [IsEstimate]        BIT            NULL,
    [TargetDate]        DATETIME       NULL,
    [PlannedDate]       DATETIME       NULL,
    [Color]             NVARCHAR (10)  NULL,
    [Description]       NVARCHAR (500) NULL,
    [BudgetCost]        FLOAT (53)     NULL,
    [ActualCost]        FLOAT (53)     NULL,
    [TaskTypeId]        NUMERIC (18)   NULL,
    [CompletionPercent] FLOAT (53)     NULL,
    [IsWoLinked]        BIT            NULL,
    [IsActive]          BIT            CONSTRAINT [DF_PM_Projects_IsActive] DEFAULT ((1)) NULL,
    [WorkingDays]       VARCHAR (100)  NULL,
    [ManagerId]         INT            NULL,
    [EntityId]          INT            NULL,
    [IsWorkflowAllowed] BIT            NULL,
    [CategoryId]        NUMERIC (18)   NULL,
    [CurrencyId]        NUMERIC (18)   NULL,
    CONSTRAINT [PK_PM_Projects] PRIMARY KEY CLUSTERED ([ProjectId] ASC)
);

