CREATE TABLE [dbo].[tbl9BH1017A] (
    [LogId]               NUMERIC (18)   IDENTITY (1, 1) NOT NULL,
    [RegionId]            NUMERIC (18)   NULL,
    [Region]              VARCHAR (100)  NULL,
    [CityId]              NUMERIC (18)   NULL,
    [City]                VARCHAR (100)  NULL,
    [TestCategoryId]      NUMERIC (18)   NULL,
    [TestCategory]        VARCHAR (100)  NULL,
    [TestTypeId]          NUMERIC (18)   NULL,
    [TestType]            VARCHAR (100)  NULL,
    [TimeStamp]           DATETIME       NULL,
    [ClusterId]           NUMERIC (18)   NULL,
    [Cluster]             NVARCHAR (50)  NULL,
    [SiteId]              NUMERIC (18)   NULL,
    [Site]                NVARCHAR (50)  NULL,
    [SectorId]            NUMERIC (18)   NULL,
    [Sector]              NVARCHAR (50)  NULL,
    [CellId]              NVARCHAR (20)  NULL,
    [LacId]               NVARCHAR (20)  NULL,
    [PciId]               NVARCHAR (20)  NULL,
    [MccId]               NVARCHAR (20)  NULL,
    [MncId]               NVARCHAR (20)  NULL,
    [Latitude]            FLOAT (53)     NULL,
    [Longitude]           FLOAT (53)     NULL,
    [ScopeId]             NUMERIC (18)   NULL,
    [Scope]               VARCHAR (100)  NULL,
    [NetworkModeId]       NUMERIC (18)   NULL,
    [NetworkMode]         VARCHAR (100)  NULL,
    [BandId]              NUMERIC (18)   NULL,
    [Band]                VARCHAR (100)  NULL,
    [CarrierId]           NUMERIC (18)   NULL,
    [Carrier]             VARCHAR (100)  NULL,
    [GsmRssi]             INT            NULL,
    [GsmRxQual]           INT            NULL,
    [WcdmaRssi]           INT            NULL,
    [WcdmaRscp]           INT            NULL,
    [WcdmaEcio]           FLOAT (53)     NULL,
    [LteRssi]             INT            NULL,
    [LteRsrp]             INT            NULL,
    [LteRsrq]             INT            NULL,
    [LteRsnr]             FLOAT (53)     NULL,
    [LteCqi]              FLOAT (53)     NULL,
    [DistanceFromSite]    FLOAT (53)     NULL,
    [AngleToSite]         FLOAT (53)     NULL,
    [FtpStatus]           BIT            NULL,
    [StackTrace]          NVARCHAR (MAX) NULL,
    [TestResult]          FLOAT (53)     NULL,
    [MoStatus]            BIT            NULL,
    [MtStatus]            BIT            NULL,
    [VolteMoStatus]       BIT            NULL,
    [VolteMtStatus]       BIT            NULL,
    [ConnectionSetupTime] FLOAT (53)     NULL,
    [SubNetworkMode]      VARCHAR (100)  NULL,
    [ActualBand]          VARCHAR (100)  NULL,
    [ActualCarrier]       VARCHAR (100)  NULL,
    [TestStatus]          BIT            NULL,
    [IsHandover]          BIT            NULL,
    [IsActive]            BIT            NULL,
    [serverTimeStamp]     DATETIME       NULL,
    [pciColor]            NVARCHAR (10)  NULL,
    [rsrpColor]           NVARCHAR (10)  NULL,
    [rsrqColor]           NVARCHAR (10)  NULL,
    [sinrColor]           NVARCHAR (10)  NULL,
    [dlColor]             NVARCHAR (10)  NULL,
    [ChColor]             NVARCHAR (10)  NULL
);

