CREATE TABLE [dbo].[temp] (
    [RegionId]         NUMERIC (18)   NOT NULL,
    [Region]           VARCHAR (100)  NOT NULL,
    [CityId]           NUMERIC (18)   NOT NULL,
    [City]             VARCHAR (100)  NOT NULL,
    [TestCategoryId]   NUMERIC (18)   NULL,
    [TestCategory]     VARCHAR (100)  NULL,
    [TestTypeId]       NUMERIC (18)   NULL,
    [TestType]         VARCHAR (100)  NULL,
    [TimeStamp]        VARCHAR (100)  NULL,
    [ClusterId]        NUMERIC (18)   NOT NULL,
    [Cluster]          VARCHAR (50)   NOT NULL,
    [SiteId]           NUMERIC (18)   NOT NULL,
    [Site]             NVARCHAR (50)  NULL,
    [SectorId]         NUMERIC (18)   NOT NULL,
    [Sector]           NVARCHAR (50)  NULL,
    [CellId]           NVARCHAR (20)  NULL,
    [LacId]            NVARCHAR (20)  NULL,
    [PciId]            NVARCHAR (20)  NULL,
    [MccId]            NVARCHAR (20)  NULL,
    [MncId]            NVARCHAR (20)  NULL,
    [Latitude]         FLOAT (53)     NULL,
    [Longitude]        FLOAT (53)     NULL,
    [ScopeId]          INT            NULL,
    [Scope]            NVARCHAR (50)  NULL,
    [NetworkModeId]    INT            NULL,
    [NetworkMode]      VARCHAR (100)  NULL,
    [BandId]           INT            NULL,
    [Band]             VARCHAR (100)  NULL,
    [CarrierId]        INT            NULL,
    [Carrier]          VARCHAR (100)  NULL,
    [GsmRssi]          INT            NULL,
    [GsmRxQual]        INT            NULL,
    [WcdmaRssi]        INT            NOT NULL,
    [WcdmaRscp]        INT            NULL,
    [WcdmaEcio]        FLOAT (53)     NULL,
    [LteRssi]          INT            NOT NULL,
    [LteRsrp]          INT            NULL,
    [LteRsrq]          INT            NULL,
    [LteRsnr]          FLOAT (53)     NULL,
    [LteCqi]           FLOAT (53)     NULL,
    [DistanceFromSite] FLOAT (53)     NULL,
    [AngleToSite]      FLOAT (53)     NULL,
    [FtpStatus]        NVARCHAR (50)  NULL,
    [StackTrace]       NVARCHAR (MAX) NULL,
    [TestResult]       FLOAT (53)     NULL,
    [SubNetworkMode]   NVARCHAR (100) NULL,
    [ActualBand]       NVARCHAR (100) NULL,
    [ActualCarrier]    NVARCHAR (100) NULL,
    [TestStatus]       BIT            NULL,
    [IsHandover]       BIT            NULL
);

