CREATE TABLE [dbo].[tmpMobility] (
    [rowID]            BIGINT         NULL,
    [Site]             NVARCHAR (50)  NULL,
    [Sector]           NVARCHAR (50)  NULL,
    [NetworkMode]      VARCHAR (100)  NULL,
    [Band]             INT            NULL,
    [Carrier]          VARCHAR (100)  NULL,
    [CellId]           NVARCHAR (20)  NULL,
    [LacId]            NVARCHAR (20)  NULL,
    [PciId]            NVARCHAR (100) NULL,
    [MccId]            NVARCHAR (20)  NULL,
    [MncId]            NVARCHAR (20)  NULL,
    [Latitude]         FLOAT (53)     NULL,
    [Longitude]        FLOAT (53)     NULL,
    [TimeStamp]        VARCHAR (100)  NULL,
    [GsmRssi]          INT            NULL,
    [GsmRxQual]        INT            NULL,
    [WcdmaRscp]        INT            NULL,
    [WcdmaEcio]        FLOAT (53)     NULL,
    [LteRsrp]          INT            NULL,
    [LteRsrq]          INT            NULL,
    [LteRsnr]          FLOAT (53)     NULL,
    [LteCqi]           FLOAT (53)     NULL,
    [DistanceFromSite] FLOAT (53)     NULL,
    [AngleToSite]      FLOAT (53)     NULL,
    [FtpStatus]        NVARCHAR (50)  NULL,
    [StackTrace]       NVARCHAR (MAX) NULL,
    [TestResult]       FLOAT (53)     NULL,
    [SubNetworkMode]   NVARCHAR (100) NULL,
    [ActualBand]       NVARCHAR (100) NULL,
    [ActualCarrier]    NVARCHAR (100) NULL,
    [IsHandover]       INT            NULL,
    [FloorId]          NUMERIC (18)   NOT NULL,
    [RRCState]         NVARCHAR (50)  NULL,
    [NRBand]           VARCHAR (100)  NULL,
    [NRCarrier]        VARCHAR (100)  NULL,
    [NRRsrp]           INT            NULL,
    [NRRsrq]           INT            NULL,
    [NRRsnr]           FLOAT (53)     NULL,
    [NRCqi]            FLOAT (53)     NULL,
    [FromPCI]          NVARCHAR (15)  NULL,
    [ToPCI]            NVARCHAR (15)  NULL
);

