//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirView.DBLayer.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AV_NemoSiteLogs
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public string Current_System { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public int fileID_Fk { get; set; }
        public string Cell { get; set; }
        public string Band { get; set; }
        public string Channel { get; set; }
        public Nullable<long> PCI_PN { get; set; }
        public Nullable<decimal> RSSI_dBm { get; set; }
        public string RSRQ_Ec_I0_db { get; set; }
        public string RSRP_RSCP_dBm { get; set; }
        public string Cell1 { get; set; }
        public string Band1 { get; set; }
        public string Channel1 { get; set; }
        public Nullable<long> PCI_PN1 { get; set; }
        public Nullable<decimal> RSSI_dBm1 { get; set; }
        public string RSRQ_Ec_I0_db1 { get; set; }
        public string RSRP_RSCP_dBm1 { get; set; }
        public string Cell2 { get; set; }
        public string Band2 { get; set; }
        public string Channel2 { get; set; }
        public Nullable<long> PCI_PN2 { get; set; }
        public Nullable<decimal> RSSI_dBm2 { get; set; }
        public string RSRQ_Ec_I0_db2 { get; set; }
        public string RSRP_RSCP_dBm2 { get; set; }
        public string Cell3 { get; set; }
        public string Band3 { get; set; }
        public string Channel3 { get; set; }
        public Nullable<long> PCI_PN3 { get; set; }
        public Nullable<decimal> RSSI_dBm3 { get; set; }
        public string RSRQ_Ec_I0_db3 { get; set; }
        public string RSRP_RSCP_dBm3 { get; set; }
        public string Cell4 { get; set; }
        public string Band4 { get; set; }
        public string Channel4 { get; set; }
        public Nullable<long> PCI_PN4 { get; set; }
        public Nullable<decimal> RSSI_dBm4 { get; set; }
        public string RSRQ_Ec_I0_db4 { get; set; }
        public string RSRP_RSCP_dBm4 { get; set; }
        public string Cell5 { get; set; }
        public string Band5 { get; set; }
        public string Channel5 { get; set; }
        public Nullable<long> PCI_PN5 { get; set; }
        public Nullable<decimal> RSSI_dBm5 { get; set; }
        public string RSRQ_Ec_I0_db5 { get; set; }
        public string RSRP_RSCP_dBm5 { get; set; }
        public string Cell6 { get; set; }
        public string Band6 { get; set; }
        public string Channel6 { get; set; }
        public Nullable<long> PCI_PN6 { get; set; }
        public Nullable<decimal> RSSI_dBm6 { get; set; }
        public string RSRQ_Ec_I0_db6 { get; set; }
        public string RSRP_RSCP_dBm6 { get; set; }
        public string Cell7 { get; set; }
        public string Band7 { get; set; }
        public string Channel7 { get; set; }
        public Nullable<long> PCI_PN7 { get; set; }
        public Nullable<decimal> RSSI_dBm7 { get; set; }
        public string RSRQ_Ec_I0_db7 { get; set; }
        public string RSRP_RSCP_dBm7 { get; set; }
        public string Cell8 { get; set; }
        public string Band8 { get; set; }
        public string Channel8 { get; set; }
        public Nullable<long> PCI_PN8 { get; set; }
        public Nullable<decimal> RSSI_dBm8 { get; set; }
        public string RSRQ_Ec_I0_db8 { get; set; }
        public string RSRP_RSCP_dBm8 { get; set; }
        public string Cell9 { get; set; }
        public string Band9 { get; set; }
        public string Channel9 { get; set; }
        public Nullable<long> PCI_PN9 { get; set; }
        public Nullable<decimal> RSSI_dBm9 { get; set; }
        public string RSRQ_Ec_I0_db9 { get; set; }
        public string RSRP_RSCP_dBm9 { get; set; }
        public string HO_Type { get; set; }
        public string Current_Channel { get; set; }
        public string Current_Band { get; set; }
        public string Attempted_System { get; set; }
        public string Attempted_PCI { get; set; }
        public string Attempted_Band { get; set; }
        public string HO_Duration_ms { get; set; }
        public string HO_Uplane_interruption_ms { get; set; }
        public string Event { get; set; }
        public string Call_Type { get; set; }
        public string Call_Direction { get; set; }
        public string MO_MTPhone_Number { get; set; }
        public string Call_Connection_Status { get; set; }
        public string Ping_Size_bytes { get; set; }
        public string RTT_ms { get; set; }
        public string Connection_Setup_Time_ms { get; set; }
        public string Current_PCI { get; set; }
        public string Attempted_Channel { get; set; }
        public string PDSCH_DL_Throughput_bits { get; set; }
        public string PUSCH_UL_Throughput_bits { get; set; }
        public string Direction { get; set; }
        public string EventFields { get; set; }
        public Nullable<decimal> SNR { get; set; }
        public Nullable<decimal> SNR1 { get; set; }
        public Nullable<decimal> SNR2 { get; set; }
        public Nullable<decimal> SNR3 { get; set; }
        public Nullable<decimal> SNR4 { get; set; }
        public Nullable<decimal> SNR5 { get; set; }
        public Nullable<decimal> SNR6 { get; set; }
        public Nullable<decimal> SNR7 { get; set; }
        public Nullable<decimal> SNR8 { get; set; }
    
        public virtual AV_LogsInfo AV_LogsInfo { get; set; }
    }
}
