CREATE TYPE [dbo].[PM_ImportList] AS TABLE (
    [Value1]  NVARCHAR (50)  NULL,
    [Value2]  NVARCHAR (50)  NULL,
    [Value3]  NVARCHAR (50)  NULL,
    [Value4]  NVARCHAR (50)  NULL,
    [Value5]  NVARCHAR (50)  NULL,
    [Value6]  NVARCHAR (50)  NULL,
    [Value7]  NVARCHAR (50)  NULL,
    [Value8]  NVARCHAR (50)  NULL,
    [Value9]  NVARCHAR (50)  NULL,
    [Value10] NVARCHAR (50)  NULL,
    [Value11] NVARCHAR (MAX) NULL,
    [Value12] NVARCHAR (MAX) NULL,
    [Value13] NVARCHAR (50)  NULL,
    [Value14] NVARCHAR (50)  NULL,
    [Value15] NVARCHAR (50)  NULL,
    [Value16] NVARCHAR (50)  NULL,
    [Value17] NVARCHAR (50)  NULL,
    [Value18] NVARCHAR (50)  NULL,
    [Value19] NVARCHAR (50)  NULL,
    [Value20] NVARCHAR (MAX) NULL);

