CREATE TYPE [dbo].[Tbl_AV_SiteTestSummary] AS TABLE (
    [SummaryId]              NUMERIC (18)   NULL,
    [LatencyRate]            FLOAT (53)     NULL,
    [DownlinkRate]           FLOAT (53)     NULL,
    [UplinkRate]             FLOAT (53)     NULL,
    [DownlinkMaxResult]      FLOAT (53)     NULL,
    [UplinkMaxResult]        FLOAT (53)     NULL,
    [PingAverageResult]      FLOAT (53)     NULL,
    [OoklaDownlinkResult]    FLOAT (53)     NULL,
    [OoklaUplinkResult]      FLOAT (53)     NULL,
    [OoklaPingResult]        FLOAT (53)     NULL,
    [MoStatus]               BIT            NULL,
    [MtStatus]               BIT            NULL,
    [VMoStatus]              BIT            NULL,
    [VMtStatus]              BIT            NULL,
    [CwHandoverStatus]       BIT            NULL,
    [Ccwhandoverstatus]      BIT            NULL,
    [ICwHandoverStatus]      BIT            NULL,
    [ICcwhandoverstatus]     BIT            NULL,
    [OoklaTestFilePath]      NVARCHAR (500) NULL,
    [OoklaRssi]              FLOAT (53)     NULL,
    [OoklaSinr]              FLOAT (53)     NULL,
    [TestLatitude]           FLOAT (53)     NULL,
    [TestLongitude]          FLOAT (53)     NULL,
    [TestRssi]               FLOAT (53)     NULL,
    [TestSinr]               FLOAT (53)     NULL,
    [StationaryTestFilePath] NVARCHAR (500) NULL,
    [CwTestFilePath]         NVARCHAR (500) NULL,
    [CcwTestFilePath]        NVARCHAR (500) NULL,
    [PingStatus]             BIT            NULL,
    [DownlinkStatus]         BIT            NULL,
    [UplinkStatus]           BIT            NULL,
    [E911Status]             BIT            NULL,
    [IsE911Performed]        BIT            NULL,
    [MimoStatus]             BIT            NULL,
    [SMtStatus]              BIT            NULL,
    [SMoStatus]              BIT            NULL,
    [MimoTestFilePath]       NVARCHAR (500) NULL,
    [SpeedTestFilePath]      NVARCHAR (500) NULL,
    [CaActiveTestFilePath]   NVARCHAR (500) NULL,
    [CaDeavticeTestFilePath] NVARCHAR (500) NULL,
    [CaSpeedTestFilePath]    NVARCHAR (500) NULL,
    [LaaSpeedTestFilePath]   NVARCHAR (500) NULL,
    [LaaSmTestFilePath]      NVARCHAR (500) NULL,
    [PhyDLSpeedMin]          FLOAT (53)     NULL,
    [PhyDLSpeedMax]          FLOAT (53)     NULL,
    [PhyDLSpeedAvg]          FLOAT (53)     NULL,
    [PhyULSpeedMin]          FLOAT (53)     NULL,
    [PhyULSpeedMax]          FLOAT (53)     NULL,
    [PhyULSpeedAvg]          FLOAT (53)     NULL,
    [IntraHOInteruptTime]    FLOAT (53)     NULL,
    [callSetupTime]          FLOAT (53)     NULL,
    [IntreHOInteruptTime]    FLOAT (53)     NULL,
    [PhyDLStatus]            BIT            NULL,
    [PhyULStatus]            BIT            NULL,
    [CADLSpeed]              FLOAT (53)     NULL,
    [CAULSpeed]              FLOAT (53)     NULL);

