CREATE TYPE [dbo].[TSS_ResponsesList] AS TABLE (
    [Value1]  NVARCHAR (MAX) NULL,
    [Value2]  NVARCHAR (MAX) NULL,
    [Value3]  NVARCHAR (MAX) NULL,
    [Value4]  NVARCHAR (MAX) NULL,
    [Value5]  NVARCHAR (MAX) NULL,
    [Value6]  NVARCHAR (MAX) NULL,
    [Value7]  NVARCHAR (MAX) NULL,
    [Value8]  NVARCHAR (MAX) NULL,
    [Value9]  NVARCHAR (MAX) NULL,
    [Value10] NVARCHAR (MAX) NULL,
    [Value11] NVARCHAR (MAX) NULL,
    [Value12] NVARCHAR (MAX) NULL,
    [Value13] NVARCHAR (MAX) NULL,
    [Value14] NVARCHAR (MAX) NULL,
    [Value15] NVARCHAR (MAX) NULL,
    [Value16] NVARCHAR (MAX) NULL,
    [Value17] NVARCHAR (MAX) NULL,
    [Value18] NVARCHAR (MAX) NULL,
    [Value19] NVARCHAR (MAX) NULL,
    [Value20] NVARCHAR (MAX) NULL);

